--------------------------------------------------------
--  文件已创建 - 星期五-一月-20-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GOODSTYPE_CHILDRENSET
--------------------------------------------------------

CREATE TABLE "C##ZHOUJIELUN"."GOODSTYPE_CHILDRENSET"
(
  "GOODSTYPE_CHILDRENSET" NUMBER(10, 0),
  "CHILDRENSET_GOOK_PK"   NUMBER(10, 0)
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
STORAGE (INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
)
TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table HT_TB_MOBILEGOODS8
--------------------------------------------------------

CREATE GLOBAL TEMPORARY TABLE "C##ZHOUJIELUN"."HT_TB_MOBILEGOODS8"
(
  "MOBILEGOODS_ID" NUMBER(19, 0)
) ON COMMIT DELETE ROWS;
--------------------------------------------------------
--  DDL for Table MOBILEGOODS_GOODSTYPE
--------------------------------------------------------

CREATE TABLE "C##ZHOUJIELUN"."MOBILEGOODS_GOODSTYPE"
(
  "COL_MOBILEGOODSTYPE"         NUMBER(19, 0),
  "COL_MOBILEGOODSTYPEMANY2ONE" NUMBER(10, 0)
) SEGMENT CREATION DEFERRED
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table MOBILEGOODS_IMAGESMAP
--------------------------------------------------------

CREATE TABLE "C##ZHOUJIELUN"."MOBILEGOODS_IMAGESMAP"
(
  "COL_IMAGES_MOBILE"       NUMBER(19, 0),
  "COL_IMAGES_INDEX_MOBILE" NUMBER(10, 0),
  "ELEMENT_IMAGES_MOBILE"   VARCHAR2(255 CHAR)
) SEGMENT CREATION DEFERRED
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table MOBILEGOODSSET_GOODSTYPE
--------------------------------------------------------

CREATE TABLE "C##ZHOUJIELUN"."MOBILEGOODSSET_GOODSTYPE"
(
  "GOODSTYPE_MOBILESET"           NUMBER(10, 0),
  "MOBILEGOODSSET_MOBILEGOODS_ID" NUMBER(19, 0)
) SEGMENT CREATION DEFERRED
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table TB_GOODSTYPE8
--------------------------------------------------------

CREATE TABLE "C##ZHOUJIELUN"."TB_GOODSTYPE8"
(
  "GOOK_PK"               NUMBER(10, 0),
  "GOODS_TYPEDESCRIPTION" LONG,
  "GOODS_TYPENAME"        VARCHAR2(40 CHAR),
  "GOODSTYPE_PARENTID"    NUMBER(10, 0)
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
STORAGE (INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
)
TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table TB_MOBILEGOODS8
--------------------------------------------------------

CREATE TABLE "C##ZHOUJIELUN"."TB_MOBILEGOODS8"
(
  "MOBILEGOODS_ID"          NUMBER(19, 0),
  "MOBILE_GOODSNUMBER"      NUMBER(10, 0),
  "MOBILE_GOODSNAME"        VARCHAR2(100 CHAR),
  "MOBILE_GOODSPRICE"       FLOAT(126),
  "MOBILE_GOODSDESCRIPTION" LONG,
  "MOBILE_OS"               VARCHAR2(20 CHAR),
  "MOBILE_MEMORY"           VARCHAR2(20 CHAR),
  "MOBILE_FRONTCAMERA"      VARCHAR2(20 CHAR),
  "MOBILE_NEWS"             VARCHAR2(300 CHAR),
  "MOBILE_BACKCAMERA"       VARCHAR2(20 CHAR),
  "MOBILE_BATTERY"          VARCHAR2(50 CHAR),
  "MOBILE_ROM"              VARCHAR2(50 CHAR),
  "MOBILE_COLOR"            VARCHAR2(20 CHAR)
) SEGMENT CREATION DEFERRED
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index SYS_C0010849
--------------------------------------------------------

CREATE UNIQUE INDEX "C##ZHOUJIELUN"."SYS_C0010849"
  ON "C##ZHOUJIELUN"."GOODSTYPE_CHILDRENSET" ("GOODSTYPE_CHILDRENSET", "CHILDRENSET_GOOK_PK")
PCTFREE 10 INITRANS 2 MAXTRANS 255
STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index UK_76OJNV8BDX1XR60FT0XPQ8YTT
--------------------------------------------------------

CREATE UNIQUE INDEX "C##ZHOUJIELUN"."UK_76OJNV8BDX1XR60FT0XPQ8YTT"
  ON "C##ZHOUJIELUN"."GOODSTYPE_CHILDRENSET" ("CHILDRENSET_GOOK_PK")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index SYS_C0010851
--------------------------------------------------------

CREATE UNIQUE INDEX "C##ZHOUJIELUN"."SYS_C0010851"
  ON "C##ZHOUJIELUN"."MOBILEGOODS_GOODSTYPE" ("COL_MOBILEGOODSTYPE")
PCTFREE 10 INITRANS 2 MAXTRANS 255
TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index SYS_C0010854
--------------------------------------------------------

CREATE UNIQUE INDEX "C##ZHOUJIELUN"."SYS_C0010854"
  ON "C##ZHOUJIELUN"."MOBILEGOODS_IMAGESMAP" ("COL_IMAGES_MOBILE", "COL_IMAGES_INDEX_MOBILE")
PCTFREE 10 INITRANS 2 MAXTRANS 255
TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index SYS_C0010857
--------------------------------------------------------

CREATE UNIQUE INDEX "C##ZHOUJIELUN"."SYS_C0010857"
  ON "C##ZHOUJIELUN"."MOBILEGOODSSET_GOODSTYPE" ("GOODSTYPE_MOBILESET", "MOBILEGOODSSET_MOBILEGOODS_ID")
PCTFREE 10 INITRANS 2 MAXTRANS 255
TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index UK_OSGQ4VRQ7A0MYGHCXF0QFJ4OE
--------------------------------------------------------

CREATE UNIQUE INDEX "C##ZHOUJIELUN"."UK_OSGQ4VRQ7A0MYGHCXF0QFJ4OE"
  ON "C##ZHOUJIELUN"."MOBILEGOODSSET_GOODSTYPE" ("MOBILEGOODSSET_MOBILEGOODS_ID")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index SYS_C0010859
--------------------------------------------------------

CREATE UNIQUE INDEX "C##ZHOUJIELUN"."SYS_C0010859"
  ON "C##ZHOUJIELUN"."TB_GOODSTYPE8" ("GOOK_PK")
PCTFREE 10 INITRANS 2 MAXTRANS 255
STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index UK_EJ6KQ1490ACP6O6XS9YFYNI8I
--------------------------------------------------------

CREATE UNIQUE INDEX "C##ZHOUJIELUN"."UK_EJ6KQ1490ACP6O6XS9YFYNI8I"
  ON "C##ZHOUJIELUN"."TB_GOODSTYPE8" ("GOODS_TYPENAME")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index SYS_C0010861
--------------------------------------------------------

CREATE UNIQUE INDEX "C##ZHOUJIELUN"."SYS_C0010861"
  ON "C##ZHOUJIELUN"."TB_MOBILEGOODS8" ("MOBILEGOODS_ID")
PCTFREE 10 INITRANS 2 MAXTRANS 255
TABLESPACE "USERS";
--------------------------------------------------------
--  Constraints for Table GOODSTYPE_CHILDRENSET
--------------------------------------------------------

ALTER TABLE "C##ZHOUJIELUN"."GOODSTYPE_CHILDRENSET"
  ADD CONSTRAINT "UK_76OJNV8BDX1XR60FT0XPQ8YTT" UNIQUE ("CHILDRENSET_GOOK_PK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE (INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE;
ALTER TABLE "C##ZHOUJIELUN"."GOODSTYPE_CHILDRENSET"
  ADD PRIMARY KEY ("GOODSTYPE_CHILDRENSET", "CHILDRENSET_GOOK_PK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE (INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE;
ALTER TABLE "C##ZHOUJIELUN"."GOODSTYPE_CHILDRENSET"
  MODIFY ("CHILDRENSET_GOOK_PK" NOT NULL ENABLE);
ALTER TABLE "C##ZHOUJIELUN"."GOODSTYPE_CHILDRENSET"
  MODIFY ("GOODSTYPE_CHILDRENSET" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HT_TB_MOBILEGOODS8
--------------------------------------------------------

ALTER TABLE "C##ZHOUJIELUN"."HT_TB_MOBILEGOODS8"
  MODIFY ("MOBILEGOODS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MOBILEGOODS_GOODSTYPE
--------------------------------------------------------

ALTER TABLE "C##ZHOUJIELUN"."MOBILEGOODS_GOODSTYPE"
  ADD PRIMARY KEY ("COL_MOBILEGOODSTYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "USERS" ENABLE;
ALTER TABLE "C##ZHOUJIELUN"."MOBILEGOODS_GOODSTYPE"
  MODIFY ("COL_MOBILEGOODSTYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MOBILEGOODS_IMAGESMAP
--------------------------------------------------------

ALTER TABLE "C##ZHOUJIELUN"."MOBILEGOODS_IMAGESMAP"
  ADD PRIMARY KEY ("COL_IMAGES_MOBILE", "COL_IMAGES_INDEX_MOBILE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "USERS" ENABLE;
ALTER TABLE "C##ZHOUJIELUN"."MOBILEGOODS_IMAGESMAP"
  MODIFY ("COL_IMAGES_INDEX_MOBILE" NOT NULL ENABLE);
ALTER TABLE "C##ZHOUJIELUN"."MOBILEGOODS_IMAGESMAP"
  MODIFY ("COL_IMAGES_MOBILE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MOBILEGOODSSET_GOODSTYPE
--------------------------------------------------------

ALTER TABLE "C##ZHOUJIELUN"."MOBILEGOODSSET_GOODSTYPE"
  ADD CONSTRAINT "UK_OSGQ4VRQ7A0MYGHCXF0QFJ4OE" UNIQUE ("MOBILEGOODSSET_MOBILEGOODS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ENABLE;
ALTER TABLE "C##ZHOUJIELUN"."MOBILEGOODSSET_GOODSTYPE"
  ADD PRIMARY KEY ("GOODSTYPE_MOBILESET", "MOBILEGOODSSET_MOBILEGOODS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "USERS" ENABLE;
ALTER TABLE "C##ZHOUJIELUN"."MOBILEGOODSSET_GOODSTYPE"
  MODIFY ("MOBILEGOODSSET_MOBILEGOODS_ID" NOT NULL ENABLE);
ALTER TABLE "C##ZHOUJIELUN"."MOBILEGOODSSET_GOODSTYPE"
  MODIFY ("GOODSTYPE_MOBILESET" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_GOODSTYPE8
--------------------------------------------------------

ALTER TABLE "C##ZHOUJIELUN"."TB_GOODSTYPE8"
  ADD CONSTRAINT "UK_EJ6KQ1490ACP6O6XS9YFYNI8I" UNIQUE ("GOODS_TYPENAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE (INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE;
ALTER TABLE "C##ZHOUJIELUN"."TB_GOODSTYPE8"
  ADD PRIMARY KEY ("GOOK_PK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE (INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE;
ALTER TABLE "C##ZHOUJIELUN"."TB_GOODSTYPE8"
  MODIFY ("GOOK_PK" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_MOBILEGOODS8
--------------------------------------------------------

ALTER TABLE "C##ZHOUJIELUN"."TB_MOBILEGOODS8"
  ADD PRIMARY KEY ("MOBILEGOODS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "USERS" ENABLE;
ALTER TABLE "C##ZHOUJIELUN"."TB_MOBILEGOODS8"
  MODIFY ("MOBILEGOODS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table GOODSTYPE_CHILDRENSET
--------------------------------------------------------

ALTER TABLE "C##ZHOUJIELUN"."GOODSTYPE_CHILDRENSET"
  ADD CONSTRAINT "FKQ9BF7TU2F7PXNGYA40OLO6PRH" FOREIGN KEY ("CHILDRENSET_GOOK_PK")
REFERENCES "C##ZHOUJIELUN"."TB_GOODSTYPE8" ("GOOK_PK") ENABLE;
ALTER TABLE "C##ZHOUJIELUN"."GOODSTYPE_CHILDRENSET"
  ADD CONSTRAINT "FK_CHILDREN" FOREIGN KEY ("GOODSTYPE_CHILDRENSET")
REFERENCES "C##ZHOUJIELUN"."TB_GOODSTYPE8" ("GOOK_PK") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MOBILEGOODS_GOODSTYPE
--------------------------------------------------------

ALTER TABLE "C##ZHOUJIELUN"."MOBILEGOODS_GOODSTYPE"
  ADD CONSTRAINT "FK_MOBILEGOODSTYPE" FOREIGN KEY ("COL_MOBILEGOODSTYPE")
REFERENCES "C##ZHOUJIELUN"."TB_MOBILEGOODS8" ("MOBILEGOODS_ID") ENABLE;
ALTER TABLE "C##ZHOUJIELUN"."MOBILEGOODS_GOODSTYPE"
  ADD CONSTRAINT "FK_MOBILEGOODSTYPEMANY2ONE" FOREIGN KEY ("COL_MOBILEGOODSTYPEMANY2ONE")
REFERENCES "C##ZHOUJIELUN"."TB_GOODSTYPE8" ("GOOK_PK") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MOBILEGOODS_IMAGESMAP
--------------------------------------------------------

ALTER TABLE "C##ZHOUJIELUN"."MOBILEGOODS_IMAGESMAP"
  ADD CONSTRAINT "FK_IAGES_MOBILE" FOREIGN KEY ("COL_IMAGES_MOBILE")
REFERENCES "C##ZHOUJIELUN"."TB_MOBILEGOODS8" ("MOBILEGOODS_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MOBILEGOODSSET_GOODSTYPE
--------------------------------------------------------

ALTER TABLE "C##ZHOUJIELUN"."MOBILEGOODSSET_GOODSTYPE"
  ADD CONSTRAINT "FKG6AEH6KS2VLI0DB1ATVJ22MNE" FOREIGN KEY ("MOBILEGOODSSET_MOBILEGOODS_ID")
REFERENCES "C##ZHOUJIELUN"."TB_MOBILEGOODS8" ("MOBILEGOODS_ID") ENABLE;
ALTER TABLE "C##ZHOUJIELUN"."MOBILEGOODSSET_GOODSTYPE"
  ADD CONSTRAINT "FK_MOBILEGOODSSET" FOREIGN KEY ("GOODSTYPE_MOBILESET")
REFERENCES "C##ZHOUJIELUN"."TB_GOODSTYPE8" ("GOOK_PK") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TB_GOODSTYPE8
--------------------------------------------------------

ALTER TABLE "C##ZHOUJIELUN"."TB_GOODSTYPE8"
  ADD CONSTRAINT "FK_PARENT" FOREIGN KEY ("GOODSTYPE_PARENTID")
REFERENCES "C##ZHOUJIELUN"."TB_GOODSTYPE8" ("GOOK_PK") ENABLE;
